### ISSUE TITLE
2.0 Documentation

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-docs-site#149]
Outline of initial 2.0 docs:
- Getting started
  - [ ] Installation & Configuration
  - [ ] Configuring sensuctl
- Overview
  - [ ] Creating a check https://github.com/sensu/sensu-docs-site/pull/191
  - [ ] Installing check executables using assets #194 
  - [ ] Reducing alert fatigue with filters #195 
  - [ ] Sending notifications with handlers #196 
  - [ ] Silencing alerts #197 
- Reference
  - [ ] Entities #198 
  - [ ] Checks #199 
  - [ ] Events #200 
  - [ ] Filters #201 
  - [ ] Mutators #202 
  - [ ] Assets #203 
  - [ ] Hooks #204 
  - [ ] RBAC #205

**Comment by cwjohnston** [comment]
> Installing checks using assets

We should be careful to separate the concept of check plugins (what to run) from the concept of check definitions (how to run them)

 > Ignoring events with filters

Maybe better framed as "Reducing noise with filters" ?

**Comment by cwjohnston** [comment]
Should handling metrics be included?

**Comment by cwjohnston** [comment]
I think Entities (née Clients) also merit their own section, perhaps preceding Checks

**Comment by grepory** [comment]
@cwjohnston 

It's yet to be understood how we handle metrics in 2.0, so no, we can't document that yet.

I don't know how to distinguish between "check" and "plug-in" without introducing terminology that will certainly be foreign to a new user. If you could suggest something that isn't as vague as "plug-in," I'd appreciate it.

"Reducing noise with filters" seems okay... But the word noise is running me the wrong way.

And agreed. Entities not being there was an oversight.

**Comment by cwjohnston** [comment]
> I don't know how to distinguish between "check" and "plug-in" without introducing terminology 

If we refer to check plugins as "check executables" would that help reduce new terminology?

**Comment by obfuscurity** [comment]
Is `sensuctl` considered the preferred interface for interacting with the system? If so, should we add a "Using sensuctl" page under "Getting started"?

**Comment by grepory** [comment]
Right now it’s the _only_ interface.

**Comment by obfuscurity** [comment]
So yeah I think it would be cool to have at least a cursory introduction to `sensuctl` usage in that section.

**Comment by grepory** [comment]
I’m not sure how “using sensuctl” looks. Is this a basic intro into “how to get help” “CLI conventions”?

**Comment by obfuscurity** [comment]
Yes, a basic introduction into its usage. If you feel it's unnecessary that's fine with me, but it feels weird to have "configuration" but not "usage". OTOH I understand why you'd have it there so /shrug.

**Comment by obfuscurity** [comment]
Can you elaborate on "Mutating events"? I think I grok what this is but I'd like to hear an explanation before I make any other judgments. :)

**Comment by grepory** [comment]
Gotcha. Usage makes sense to me as well.

Events can be mutated in the event pipeline as they flow through Sensu. I.e. any field in the struct could be modified before being passed to a handler. We could gloss over it until we can identify a high level problem that mutators solve and approach the doc from that angle.

**Comment by obfuscurity** [comment]
Ok yeah that's what I figured. SGTM.

**Comment by obfuscurity** [comment]
Is RBAC the only supported auth/access mechanism?

**Comment by grepory** [comment]
Yes. For now, Sensu’s internal authn/authz mechanisms are all that are available. It’s also required.

**Comment by obfuscurity** [comment]
I was just thinking that "Authentication" might be a better section header there if we have other mechanisms. But if that's the only one then it's probably fine as-is.

**Comment by obfuscurity** [comment]
Aside from the aforementioned comments, LGTM. 👍

**Comment by grepory** [comment]
Updated the TOC with feedback. I'll start working on docs this week.

**Comment by grepory** [comment]
OK. So to lay the ground rules for future documentation:

Take a look at the table of contents. Under overview, you'll see statements of the form:

"<solution to problem> with/using <feature name>"

E.g. For proxy check requests, it might be something like: "Monitoring external resources with proxy check requests"

We're going to be putting all of our 2.0 documentation under `content/sensu-core/2.0` for now.

A question I have about versioning documentation for 2.0, though:

We release 2.0 every week, and the software is changing just as rapidly. Features may be changing, data structures... Can we maybe do some expectation setting there for when we cut a new docs version?

**Comment by obfuscurity** [comment]
Your comment made me realize we should have a page in there for Release Notes. And in each of those I'd like to see a link to the respective tag for that doc version. Make sense?

**Comment by grepory** [comment]
Yeah. I'd like to not commit us to adding 52 versions of the 2.0 docs a year, though. We should talk about when we add new versions of the docs.

**Comment by grepory** [comment]
Spoke with Jason about this. We want to tag the git repo when we release new verions of the software, so you can associate a version of Sensu 2 with a version of the sensu-docs-site repository. This may require some juggling on our part during the release, but hopefully we can automate this and make it painless.

**Comment by cwjohnston** [comment]
I tried to follow the [alpha docs wrt creating assets and associating them with a check](https://github.com/sensu/sensu-alpha-documentation/blob/master/06-checks-and-assets.md#assets) but it's not working.

```
$ sensuctl asset create monitoring-plugins/linux64 --url "http://sensu-sparkle.s3.amazonaws.com/sensu-assets/monitoring-plugins.tar.gz" --sha512 8cf4738aaca677fea7cc850dc45be41c8bf552d275921d9e6af8e72ba86868e24adb6d2374fb7a05f616b4cc3d0378da3e3121c43dd05112d376c8c1c3190409 --filter "System.OS=='linux'" --filter "System.Arch == 'amd64'"
...
$ sensuctl asset list
             Name                                           URL                                  Hash    
 ──────────────────────────── ──────────────────────────────────────────────────────────────── ───────── 
  monitoring-plugins/linux64   //sensu-sparkle.s3.amazonaws.com/.../monitoring-plugins.tar.gz   8cf4738 
```

In the agent logs, I can see the check request message come through:

```
Feb  5 17:32:38 localhost sensu-agent[19909]: {"component":"agent","level":"info","msg":"message received - type: check_request message: {\"config\":{\"check_hooks\":null,\"command\":\"check_ping -H 192.168.250.123 -w 50,5% -c 100,10%\",\"environment\":\"default\",\"handlers\":[\"pushover\"],\"high_flap_threshold\":0,\"interval\":60,\"low_flap_threshold\":0,\"name\":\"skybell_ping\",\"organization\":\"default\",\"proxy_entity_id\":\"\",\"publish\":true,\"runtime_assets\":[\"monitoring-plugins/linux64\"],\"stdin\":false,\"subdue\":null,\"subscriptions\":[\"skybell\"],\"timeout\":0,\"Environment\":\"default\"},\"assets\":[{\"name\":\"monitoring-plugins/linux64\",\"url\":\"http://sensu-sparkle.s3.amazonaws.com/sensu-assets/monitoring-plugins.tar.gz\",\"sha512\":\"8cf4738aaca677fea7cc850dc45be41c8bf552d275921d9e6af8e72ba86868e24adb6d2374fb7a05f616b4cc3d0378da3e3121c43dd05112d376c8c1c3190409\",\"metadata\":{},\"filters\":[\"System.OS=='linux'\",\"System.Arch == 'amd64'\"],\"organization\":\"default\"}],\"hooks\":null}","time":"2018-02-05T17:32:38Z"}
```

But the check fails because `check_ping` (from asset) is not found:

```
skybell_ping   sh: 1: check_ping: not found
```

**Comment by obfuscurity** [comment]
@grepory Not sure where we want to add it but I'd like to request a guide for upgrading from 1.x to 2.0 (sensu-go, not SE).

**Comment by grepory** [comment]
I'm closing this in favor of a milestone. I'd like to hold off on a 1.x->2.x upgrade doc until we have an actual upgrade path.
